# Generated by Django 4.1.7 on 2023-02-17 04:04

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_remove_usercategory_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
