# Generated by Django 4.1.7 on 2023-02-17 04:08

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
