# Generated by Django 4.1.6 on 2023-02-15 23:29

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[("spending", "spending"), ("saving", "saving")],
                default="savings",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
