# Generated by Django 4.1.7 on 2023-03-18 00:51

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="amount",
        ),
        migrations.AddField(
            model_name="account",
            name="initial_balance",
            field=models.FloatField(default=0),
        ),
    ]
