# Generated by Django 4.1.7 on 2023-02-17 03:27

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_account_unique_account_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="unique_account",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("name", "user_id"), name="unique_account"
            ),
        ),
    ]
