# Generated by Django 4.1.7 on 2023-03-18 01:00

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_account_amount_account_initial_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
