# Generated by Django 4.1.7 on 2023-04-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_account_initial_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="nickname",
        ),
    ]
