# Generated by Django 4.1.7 on 2023-04-30 14:13

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_account_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency_code",
            field=models.CharField(default="CAD", max_length=3),
            preserve_default=False,
        ),
    ]
