# Generated by Django 4.1.7 on 2023-03-20 13:12

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="date_classified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
