# Generated by Django 4.1.7 on 2023-02-17 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transaction_user_category_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user_category_id",
        ),
    ]
