# Generated by Django 4.1.7 on 2023-02-18 18:33

import django.db.models.deletion
from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_remove_account_unique_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0005_alter_category_name"),
        ("transaction", "0003_remove_transaction_user_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="account.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="category.category",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
